// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX80g1g2RUFK4HYiz0xmxaNGW5dMvaaY4',
    appId: '1:341210438642:android:f305483d616d3e4cf7296b',
    messagingSenderId: '341210438642',
    projectId: 'capri-stok',
    storageBucket: 'capri-stok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkjhXcgVSkHltAi3cJncSPR51XzzHRa9Y',
    appId: '1:341210438642:ios:766bb336fb5eb85cf7296b',
    messagingSenderId: '341210438642',
    projectId: 'capri-stok',
    storageBucket: 'capri-stok.firebasestorage.app',
    iosBundleId: 'com.example.capri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7p4y7DWkuyZfnhk4RJjDgRnqW6m8BZk',
    appId: '1:341210438642:web:e1900d3b43bf8501f7296b',
    messagingSenderId: '341210438642',
    projectId: 'capri-stok',
    authDomain: 'capri-stok.firebaseapp.com',
    storageBucket: 'capri-stok.firebasestorage.app',
    measurementId: 'G-T9K7XTN5C8',
  );
}
